version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: rogoyanov_nginx
    restart: always
    volumes:
      - ./docker/nginx/nginx.develop.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - frontend
      - backend
    networks:
      - rogoyanov_network

  mongodb:
    image: mongo:7.0
    container_name: rogoyanov_mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test_database
#    ports:
#      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - rogoyanov_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rogoyanov_backend
    restart: always
#    ports:
#      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/test_database
      - PORT=8001
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - rogoyanov_network
    command: uvicorn server:app --host 0.0.0.0 --port 8001 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rogoyanov_frontend
    restart: no
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - rogoyanov_network
    command: yarn start

networks:
  rogoyanov_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
